/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myrepositories;

public class App {

   
    public static void main(String arg[]) {
  
  
        // Prints "Hello, World" to the terminal window.
        System.out.println("Hello, World");
    }

}
